/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./*.html"],
  theme: {
    extend: {
      colors: {
        // Search & Archive tokens
        "inverse-primary": "#c3c0ff",
        "outline": "#777587",
        "surface": "#f8f9ff",
        "surface-tint": "#4d44e3",
        "secondary-fixed": "#e9ddff",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "surface-variant": "#e1e2e8",
        "on-secondary-fixed": "#23005c",
        "on-error": "#ffffff",
        "tertiary-container": "#885500",
        "secondary-fixed-dim": "#d0bcff",
        "on-surface-variant": "#464555",
        "on-primary-container": "#dad7ff",
        "inverse-on-surface": "#eff0f6",
        "background": "#f8f9ff",
        "inverse-surface": "#2e3135",
        "on-surface": "#191c20",
        "surface-container-high": "#e7e8ee",
        "secondary": "#6b38d4",
        "tertiary": "#684000",
        "error": "#ba1a1a",
        "surface-container-low": "#f2f3f9",
        "surface-bright": "#f8f9ff",
        "primary": "#3525cd",
        "on-primary-fixed-variant": "#3323cc",
        "primary-fixed-dim": "#c3c0ff",
        "surface-container-highest": "#e1e2e8",
        "outline-variant": "#c7c4d8",
        "tertiary-fixed": "#ffddb8",
        "surface-container": "#eceef3",
        "on-secondary-fixed-variant": "#5516be",
        "on-tertiary-fixed-variant": "#653e00",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#ffd4a4",
        "primary-fixed": "#e2dfff",
        "secondary-container": "#8455ef",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#ffb95f",
        "on-background": "#191c20",
        "on-tertiary-fixed": "#2a1700",
        "on-primary-fixed": "#0f0069",
        "primary-container": "#4f46e5",
        "on-primary": "#ffffff",
        "surface-dim": "#d8dae0",
        "on-secondary-container": "#fffbff",
        "cyan-accent": "#00e5ff",
        "yellow-accent": "#ffea00",
        // Landing Page tokens
        "neon-green": "#39FF14",
        "soft-purple": "#B2A4FF",
        // Landing Page primary overrides (scoped separately in its own config block)
        // Note: "primary" for landing is #FF3DBC — but we define it per-file via CSS vars
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Inter"],
        "label": ["Inter"],
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
        "extra": "2rem",
        "mega": "3rem",
      },
    },
  },
  plugins: [],
}
